import { TarokkaCard } from '@/types';

const tarokkaCards: TarokkaCard[] = [
	{
		id: 'Back',
		name: 'Card Back',
		card: 'Back of card',
		description: 'Back of card',
		aria: 'Back of card',
		back: true,
		suit: null,
		url: '/img/tarokka/Back.jpg',
	},
	{
		id: 'Coins_01_Swashbuckler',
		name: 'Swashbuckler',
		card: 'One of Coins',
		description: 'Those who like money yet give it up freely; likable rogues and rapscallions',
		aria: 'Coins 01 Swashbuckler',
		back: false,
		suit: 'Coins',
		url: '/img/tarokka/Coins_01_Swashbuckler.jpeg',
	},
	{
		id: 'Coins_02_Philanthropist',
		name: 'Philanthropist',
		card: 'Two of Coins',
		description:
			'Charity and giving on a grand scale; those who use wealth to fight evil and sickness',
		aria: 'Coins 02 Philanthropist',
		back: false,
		suit: 'Coins',
		url: '/img/tarokka/Coins_02_Philanthropist.jpeg',
	},
	{
		id: 'Coins_03_Trader',
		name: 'Trader',
		card: 'Three of Coins',
		description: 'Commerce; smuggling and black markets; fair and equitable trades',
		aria: 'Coins 03 Trader',
		back: false,
		suit: 'Coins',
		url: '/img/tarokka/Coins_03_Trader.jpeg',
	},
	{
		id: 'Coins_04_Merchant',
		name: 'Merchant',
		card: 'Four of Coins',
		description:
			'A rare commodity or business opportunity; deceitful or dangerous business transactions',
		aria: 'Coins 04 Merchant',
		back: false,
		suit: 'Coins',
		url: '/img/tarokka/Coins_04_Merchant.jpeg',
	},
	{
		id: 'Coins_05_GuildMember',
		name: 'Guild Member',
		card: 'Five of Coins',
		description: "Like-minded individuals joined together in a common goal; pride in one's work",
		aria: 'Coins 05 Guild Member',
		back: false,
		suit: 'Coins',
		url: '/img/tarokka/Coins_05_GuildMember.jpeg',
	},
	{
		id: 'Coins_06_Beggar',
		name: 'Beggar',
		card: 'Six of Coins',
		description: 'Sudden change in economic status or fortune',
		aria: 'Coins 06 Beggar',
		back: false,
		suit: 'Coins',
		url: '/img/tarokka/Coins_06_Beggar.jpeg',
	},
	{
		id: 'Coins_07_Thief',
		name: 'Thief',
		card: 'Seven of Coins',
		description:
			'Those who steal or burgle; a loss of property, beauty, innocence, friendship, or reputation',
		aria: 'Coins 07 Thief',
		back: false,
		suit: 'Coins',
		url: '/img/tarokka/Coins_07_Thief.jpeg',
	},
	{
		id: 'Coins_08_TaxCollector',
		name: 'Tax Collector',
		card: 'Eight of Coins',
		description: 'Corruption; honesty in an otherwise corrupt government or organization',
		aria: 'Coins 08 Tax Collector',
		back: false,
		suit: 'Coins',
		url: '/img/tarokka/Coins_08_TaxCollector.png',
	},
	{
		id: 'Coins_09_Miser',
		name: 'Miser',
		card: 'Nine of Coins',
		description:
			'Hoarded wealth; those who are irreversibly unhappy or who think money is meaningless',
		aria: 'Coins 09 Miser',
		back: false,
		suit: 'Coins',
		url: '/img/tarokka/Coins_09_Miser.jpeg',
	},
	{
		id: 'Coins_10_Rogue',
		name: 'Rogue',
		card: 'Master of Coins',
		description:
			'Anyone for whom money is important; those who believe money is the key to their success',
		aria: 'Coins 10 Rogue',
		back: false,
		suit: 'Coins',
		url: '/img/tarokka/Coins_10_Rogue.jpeg',
	},
	{
		id: 'Glyphs_01_Monk',
		name: 'Monk',
		card: 'One of Glyphs',
		description:
			'Serenity; inner strength and self-reliance; supreme confidence bereft of arrogance',
		aria: 'Glyphs 01 Monk',
		back: false,
		suit: 'Glyphs',
		url: '/img/tarokka/Glyphs_01_Monk.jpeg',
	},
	{
		id: 'Glyphs_02_Missionary',
		name: 'Missionary',
		card: 'Two of Glyphs',
		description:
			'Those who spread wisdom and faith to others; warnings of the spread of fear and ignorance',
		aria: 'Glyphs 02 Missionary',
		back: false,
		suit: 'Glyphs',
		url: '/img/tarokka/Glyphs_02_Missionary.jpeg',
	},
	{
		id: 'Glyphs_03_Healer',
		name: 'Healer',
		card: 'Three of Glyphs',
		description:
			'Healing; a contagious illness, disease, or curse; those who practice the healing arts',
		aria: 'Glyphs 03 Healer',
		back: false,
		suit: 'Glyphs',
		url: '/img/tarokka/Glyphs_03_Healer.jpeg',
	},
	{
		id: 'Glyphs_04_Shepherd',
		name: 'Shepherd',
		card: 'Four of Glyphs',
		description:
			'Those who protect others; one who bears a burden far too great to be shouldered alone',
		aria: 'Glyphs 04 Shepherd',
		back: false,
		suit: 'Glyphs',
		url: '/img/tarokka/Glyphs_04_Shepherd.jpeg',
	},
	{
		id: 'Glyphs_05_Druid',
		name: 'Druid',
		card: 'Five of Glyphs',
		description:
			'The ambivalence and cruelty of nature and those who feel drawn to it; inner turmoil',
		aria: 'Glyphs 05 Druid',
		back: false,
		suit: 'Glyphs',
		url: '/img/tarokka/Glyphs_05_Druid.jpeg',
	},
	{
		id: 'Glyphs_06_Anarchist',
		name: 'Anarchist',
		card: 'Six of Glyphs',
		description: 'A fundamental change brought on by one whose beliefs are being put to the test',
		aria: 'Glyphs 06 Anarchist',
		back: false,
		suit: 'Glyphs',
		url: '/img/tarokka/Glyphs_06_Anarchist.jpeg',
	},
	{
		id: 'Glyphs_07_Charlatan',
		name: 'Charlatan',
		card: 'Seven of Glyphs',
		description: 'Liars; those who profess to believe one thing but actually believe another',
		aria: 'Glyphs 07 Charlatan',
		back: false,
		suit: 'Glyphs',
		url: '/img/tarokka/Glyphs_07_Charlatan.jpeg',
	},
	{
		id: 'Glyphs_08_Bishop',
		name: 'Bishop',
		card: 'Eight of Glyphs',
		description: 'Strict adherence to a code or a belief; those who plot, plan, and scheme',
		aria: 'Glyphs 08 Bishop',
		back: false,
		suit: 'Glyphs',
		url: '/img/tarokka/Glyphs_08_Bishop.jpeg',
	},
	{
		id: 'Glyphs_09_Traitor',
		name: 'Traitor',
		card: 'Nine of Glyphs',
		description: 'Betrayal by someone close and trusted; a weakening or loss of faith',
		aria: 'Glyphs 09 Traitor',
		back: false,
		suit: 'Glyphs',
		url: '/img/tarokka/Glyphs_09_Traitor.jpeg',
	},
	{
		id: 'Glyphs_10_Priest',
		name: 'Priest',
		card: 'Master of Glyphs',
		description: 'Enlightenment; those who follow a deity, a system of values, or a higher purpose',
		aria: 'Glyphs 10 Priest',
		back: false,
		suit: 'Glyphs',
		url: '/img/tarokka/Glyphs_10_Priest.jpeg',
	},
	{
		id: 'Stars_01_Transmuter',
		name: 'Transmuter',
		card: 'One of Stars',
		description:
			'A new discovery; the coming of unexpected things; unforeseen consequences and chaos',
		aria: 'Stars 01 Transmuter',
		back: false,
		suit: 'Stars',
		url: '/img/tarokka/Stars_01_Transmuter.jpeg',
	},
	{
		id: 'Stars_02_Diviner',
		name: 'Diviner',
		card: 'Two of Stars',
		description:
			'The pursuit of knowledge tempered by wisdom; truth and honesty; sages and prophecy',
		aria: 'Stars 02 Diviner',
		back: false,
		suit: 'Stars',
		url: '/img/tarokka/Stars_02_Diviner.jpeg',
	},
	{
		id: 'Stars_03_Enchanter',
		name: 'Enchanter',
		card: 'Three of Stars',
		description: 'Inner turmoil that comes from confusion, fear of failure, or false information',
		aria: 'Stars 03 Enchanter',
		back: false,
		suit: 'Stars',
		url: '/img/tarokka/Stars_03_Enchanter.png',
	},
	{
		id: 'Stars_04_Abjurer',
		name: 'Abjurer',
		card: 'Four of Stars',
		description:
			'Those guided by logic and reasoning; warns of an overlooked clue or piece of information',
		aria: 'Stars 04 Abjurer',
		back: false,
		suit: 'Stars',
		url: '/img/tarokka/Stars_04_Abjurer.jpeg',
	},
	{
		id: 'Stars_05_Elementalist',
		name: 'Elementalist',
		card: 'Five of Stars',
		description:
			'The triumph of nature over civilization; natural disasters and bountiful harvests',
		aria: 'Stars 05 Elementalist',
		back: false,
		suit: 'Stars',
		url: '/img/tarokka/Stars_05_Elementalist.jpeg',
	},
	{
		id: 'Stars_06_Evoker',
		name: 'Evoker',
		card: 'Six of Stars',
		description:
			"Magical or supernatural power that can't be controlled; magic for destructive ends",
		aria: 'Stars 06 Evoker',
		back: false,
		suit: 'Stars',
		url: '/img/tarokka/Stars_06_Evoker.jpeg',
	},
	{
		id: 'Stars_07_Illusionist',
		name: 'Illusionist',
		card: 'Seven of Stars',
		description:
			'Lies and deceit; grand conspiracies; secret societies; the presence of a dupe or a saboteur',
		aria: 'Stars 07 Illusionist',
		back: false,
		suit: 'Stars',
		url: '/img/tarokka/Stars_07_Illusionist.jpeg',
	},
	{
		id: 'Stars_08_Necromancer',
		name: 'Necromancer',
		card: 'Eight of Stars',
		description: 'Unnatural events and unhealthy obsessions; those who follow a destructive path',
		aria: 'Stars 08 Necromancer',
		back: false,
		suit: 'Stars',
		url: '/img/tarokka/Stars_08_Necromancer.jpeg',
	},
	{
		id: 'Stars_09_Conjurer',
		name: 'Conjurer',
		card: 'Nine of Stars',
		description:
			'The coming of an unexpected supernatural threat; those who think of themselves as gods',
		aria: 'Stars 09 Conjurer',
		back: false,
		suit: 'Stars',
		url: '/img/tarokka/Stars_09_Conjurer.jpeg',
	},
	{
		id: 'Stars_10_Wizard',
		name: 'Wizard',
		card: 'Master of Stars',
		description:
			'Mystery and riddles; the unknown; those who crave magical power and great knowledge',
		aria: 'Stars 10 Wizard',
		back: false,
		suit: 'Stars',
		url: '/img/tarokka/Stars_10_Wizard.jpeg',
	},
	{
		id: 'Swords_01_Avenger',
		name: 'Avenger',
		card: 'One of Swords',
		description:
			'Justice and revenge for great wrongs; those on a quest to rid the world of great evil',
		aria: 'Swords 01 Avenger',
		back: false,
		suit: 'Swords',
		url: '/img/tarokka/Swords_01_Avenger.jpeg',
	},
	{
		id: 'Swords_02_Paladin',
		name: 'Paladin',
		card: 'Two of Swords',
		description: 'Just and noble warriors; those who live by a code of honor and integrity',
		aria: 'Swords 02 Paladin',
		back: false,
		suit: 'Swords',
		url: '/img/tarokka/Swords_02_Paladin.jpeg',
	},
	{
		id: 'Swords_03_Soldier',
		name: 'Soldier',
		card: 'Three of Swords',
		description: 'War and sacrifice; the stamina to endure great hardship',
		aria: 'Swords 03 Soldier',
		back: false,
		suit: 'Swords',
		url: '/img/tarokka/Swords_03_Soldier.jpeg',
	},
	{
		id: 'Swords_04_Mercenary',
		name: 'Mercenary',
		card: 'Four of Swords',
		description: 'Inner strength and fortitude; those who fight for power or wealth',
		aria: 'Swords 04 Mercenary',
		back: false,
		suit: 'Swords',
		url: '/img/tarokka/Swords_04_Mercenary.jpeg',
	},
	{
		id: 'Swords_05_Myrmidon',
		name: 'Myrmidon',
		card: 'Five of Swords',
		description:
			'Great heroes; a sudden reversal of fate; the triumph of the underdog over a mighty enemy',
		aria: 'Swords 05 Myrmidon',
		back: false,
		suit: 'Swords',
		url: '/img/tarokka/Swords_05_Myrmidon.jpeg',
	},
	{
		id: 'Swords_06_Berserker',
		name: 'Berserker',
		card: 'Six of Swords',
		description: 'The brutal and barbaric side of warfare; bloodlust; those with a bestial nature',
		aria: 'Swords 06 Berserker',
		back: false,
		suit: 'Swords',
		url: '/img/tarokka/Swords_06_Berserker.jpeg',
	},
	{
		id: 'Swords_07_HoodedOne',
		name: 'Hooded One',
		card: 'Seven of Swords',
		description: 'Bigotry, intolerance, and xenophobia; a mysterious presence or newcomer',
		aria: 'Swords 07 Hooded One',
		back: false,
		suit: 'Swords',
		url: '/img/tarokka/Swords_07_HoodedOne.jpeg',
	},
	{
		id: 'Swords_08_Dictator',
		name: 'Dictator',
		card: 'Eight of Swords',
		description:
			'All that is wrong with government and leadership; those who rule through fear and violence',
		aria: 'Swords 08 Dictator',
		back: false,
		suit: 'Swords',
		url: '/img/tarokka/Swords_08_Dictator.jpeg',
	},
	{
		id: 'Swords_09_Torturer',
		name: 'Torturer',
		card: 'Nine of Swords',
		description:
			'The coming of suffering or merciless cruelty; one who is irredeemably evil or sadistic',
		aria: 'Swords 09 Torturer',
		back: false,
		suit: 'Swords',
		url: '/img/tarokka/Swords_09_Torturer.jpeg',
	},
	{
		id: 'Swords_10_Warrior',
		name: 'Warrior',
		card: 'Master of Swords',
		description:
			'Strength and force personified; violence; those who use force to accomplish their goals',
		aria: 'Swords 10 Warrior',
		back: false,
		suit: 'Swords',
		url: '/img/tarokka/Swords_10_Warrior.jpeg',
	},
	{
		id: 'Crowns_Artifact',
		name: 'Artifact',
		card: 'The Artifact',
		description:
			'The importance of some physical object that must be obtained, protected, or destroyed at all costs',
		aria: 'High Deck Artifact',
		back: false,
		suit: 'High Deck',
		url: '/img/tarokka/Crowns_Artifact.jpeg',
	},
	{
		id: 'Crowns_Beast',
		name: 'Beast',
		card: 'The Beast',
		description:
			'Great rage or passion; something bestial or malevolent hiding in plain sight or lurking just below the surface',
		aria: 'High Deck Beast',
		back: false,
		suit: 'High Deck',
		url: '/img/tarokka/Crowns_Beast.jpeg',
	},
	{
		id: 'Crowns_BrokenOne',
		name: 'Broken One',
		card: 'The Broken One',
		description:
			'Defeat, failure, and despair; the loss of something or someone important, without which one feels incomplete',
		aria: 'High Deck Broken One',
		back: false,
		suit: 'High Deck',
		url: '/img/tarokka/Crowns_BrokenOne.jpeg',
	},
	{
		id: 'Crowns_Darklord',
		name: 'Darklord',
		card: 'The Darklord',
		description:
			'A single, powerful individual of an evil nature, one whose goals have enormous and far-reaching consequences',
		aria: 'High Deck Darklord',
		back: false,
		suit: 'High Deck',
		url: '/img/tarokka/Crowns_Darklord.jpeg',
	},
	{
		id: 'Crowns_Donjon',
		name: 'Donjon',
		card: 'The Donjon',
		description:
			"Isolation and imprisonment; being so conservative in thinking as to be a prisoner of one's own beliefs",
		aria: 'High Deck Donjon',
		back: false,
		suit: 'High Deck',
		url: '/img/tarokka/Crowns_Donjon.jpeg',
	},
	{
		id: 'Crowns_Executioner',
		name: 'Executioner',
		card: 'The Executioner',
		description:
			'The imminent death of one rightly or wrongly convicted of a crime; false accusations and unjust prosecution',
		aria: 'High Deck Executioner',
		back: false,
		suit: 'High Deck',
		url: '/img/tarokka/Crowns_Executioner.jpeg',
	},
	{
		id: 'Crowns_Ghost',
		name: 'Ghost',
		card: 'The Ghost',
		description:
			'The looming past; the return of an old enemy or the discovery of a secret buried long ago',
		aria: 'High Deck Ghost',
		back: false,
		suit: 'High Deck',
		url: '/img/tarokka/Crowns_Ghost.jpeg',
	},
	{
		id: 'Crowns_Horseman',
		name: 'Horseman',
		card: 'The Horseman',
		description:
			'Death; disaster in the form of the loss of wealth or property, a horrible defeat, or the end of a bloodline',
		aria: 'High Deck Horseman',
		back: false,
		suit: 'High Deck',
		url: '/img/tarokka/Crowns_Horseman.jpeg',
	},
	{
		id: 'Crowns_Innoncent',
		name: 'Innocent',
		card: 'The Innoncent',
		description:
			'A being of great importance whose life is in danger (who might be helpless or simply unaware of the peril)',
		aria: 'High Deck Innocent',
		back: false,
		suit: 'High Deck',
		url: '/img/tarokka/Crowns_Innoncent.jpeg',
	},
	{
		id: 'Crowns_Marionette',
		name: 'Marionette',
		card: 'The Marionette',
		description:
			'The presence of a spy or a minion of some greater power; an encounter with a puppet or an underling',
		aria: 'High Deck Marionette',
		back: false,
		suit: 'High Deck',
		url: '/img/tarokka/Crowns_Marionette.jpeg',
	},
	{
		id: 'Crowns_Mists',
		name: 'Mists',
		card: 'The Mists',
		description:
			"Something unexpected or mysterious that can't be avoided; a great quest or journey that will try one's spirit",
		aria: 'High Deck Mists',
		back: false,
		suit: 'High Deck',
		url: '/img/tarokka/Crowns_Mists.jpeg',
	},
	{
		id: 'Crowns_Raven',
		name: 'Raven',
		card: 'The Raven',
		description:
			'A hidden source of information; a fortunate turn of events; a secret potential for good',
		aria: 'High Deck Raven',
		back: false,
		suit: 'High Deck',
		url: '/img/tarokka/Crowns_Raven.jpeg',
	},
	{
		id: 'Crowns_Seer',
		name: 'Seer',
		card: 'The Seer',
		description:
			'Inspiration and keen intellect; a future event, the outcome of which will hinge on a clever mind',
		aria: 'High Deck Seer',
		back: false,
		suit: 'High Deck',
		url: '/img/tarokka/Crowns_Seer.jpeg',
	},
	{
		id: 'Crowns_Tempter',
		name: 'Tempter',
		card: 'The Tempter',
		description:
			'One who has been compromised or led astray by temptation or foolishness; one who tempts others for evil ends',
		aria: 'High Deck Tempter',
		back: false,
		suit: 'High Deck',
		url: '/img/tarokka/Crowns_Tempter.png',
	},
];

export default tarokkaCards;
